### ISSUE TITLE
Nested list is not rendered

### ISSUE THREAD

**Issue by natenadze1102** [nitesh9001/multi-nested-select#6]
import React, { useEffect, useRef, useState } from "react";
import { NestedSelect } from "multi-nested-select";
import './App.css';
const data = [
  {
    name: "Georgia",
    code: "AF",
    zones: ['Tbilisi,Gori'],
    continent: "Asia",
    provinceKey: "REGION"
  }
];
function App() {
  const ref = useRef();
  const [response, setResponse] = useState([]);

  const callbackFUnction = (value) => {
    console.log(value);
    setResponse(value);
  };

  useEffect(() => {
    const handleClickOutside = (event) => {
      if (ref.current && !ref.current.contains(event.target)) {
        // alert("sving fat");
      }
    };
    document.addEventListener("click", handleClickOutside, true);
    return () => {
      document.removeEventListener("click", handleClickOutside, true);
    };
  });
  return (
    <div className="App">
      <NestedSelect
        showCustomList={data}
        buttonContent="Save Selected"
        enableButton={true}
        state={true}
        width={450}
        height={200}
        leading={true}
        chip={false}
        placeholderCtx={true}
        trailing={true}
        trailingIcon={true}
        inputClass="myCustom_text"
        continent={false}
        dropDownClass="myCustom_dropbox"
        selectedValue={data}
        expandChip={true}

      />
    </div>
  );
}

export default App;.

The result i have is :
![image](https://user-images.githubusercontent.com/61623737/209673008-964227f8-3999-4318-9a29-b2b2d4ccac6f.png)

**Comment by nitesh9001** [comment]
Hey @natenadze1102 ,
You are passing wrong data ,  you should be passing name with correct code, continent and for info Georgia has no regions (**data pointing to other source, it may be wrong).
```
const data = [
    {
      name: "Georgia",
      code: "GE",
      zones: [],
      continent: "Europe",
      provinceKey: "REGION"
    }
  ];
```
